name: Development workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      run: |
        yarn install --production
        yarn build --if-present
        yarn start
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_SECRET_API }}
          heroku_app_name: 'gumtree-parser-api'
          heroku_email: 'vasilets.seven@gmail.com'
